### ISSUE TITLE
Milestone 4 to do

### ISSUE THREAD

**Issue by SamEdwardes** [UBC-MDS/DSCI_532_L01_group101_project2#12]
- [x] Build app layout @SamEdwardes 
- [x] Deploying the app to heroku @agdal1125 
- [x] Write reflect as required in [milestone 4 description](https://github.ubc.ca/MDS-2019-20/DSCI_532_viz-2_students/blob/master/release/milestone4/milestone4.md#reflection-10) @zoepan00 
- [ ] Address comments in issue #9 @zoepan00

**Comment by SamEdwardes** [comment]
App layout was created in #8
